ETL
aiplanethub/genai-stack pull request #24
Opened 2023-08-31 10:23 UTC by sam-aiplanet

2023-09-04 12:41 UTC, nikhilchintawar requested changes

2023-09-04 12:41 UTC, nikhilchintawar commented on genai_stack/etl/airbyte.py
> +        if api_key:
How we're handling when api key is not present?

2023-09-04 12:41 UTC, nikhilchintawar commented on genai_stack/etl/utils.py
> +    document: LangDocument
Document has the file right like pdf, text?

2023-09-04 12:59 UTC, sam-aiplanet commented on genai_stack/etl/airbyte.py
> +        if api_key:
there is an else condition which adds the default credentials for airbyte

2023-09-05 06:01 UTC, sam-aiplanet commented on genai_stack/etl/airbyte.py
> +        if api_key:
done - [62fc72d](https://github.com/aiplanethub/genai-stack/pull/24/commits/62fc72d42a0c81bffbfc9e214f364fbbd7be80ed)

2023-09-05 06:01 UTC, sam-aiplanet commented on genai_stack/etl/airbyte.py
> +class AirbyteETL(BaseETL):
done - [62fc72d](https://github.com/aiplanethub/genai-stack/pull/24/commits/62fc72d42a0c81bffbfc9e214f364fbbd7be80ed)

2023-09-05 06:10 UTC, nikhilaiplanet commented on genai_stack/etl/airbyte.py
> +        if api_key:
Then why do we need this condition? It will work without condition also as here if & else both have the same logic

2023-09-05 06:13 UTC, sam-aiplanet commented on genai_stack/etl/airbyte.py
> +        if api_key:
Fixed - [2ed927a](https://github.com/aiplanethub/genai-stack/pull/24/commits/2ed927aac64589dd4069ae0cda9dab8ccc4b551c)

2023-09-05 06:14 UTC, nikhilaiplanet approved these changes

2023-09-05 06:16 UTC, merged