Addition of AzureChatOpenAI model
aiplanethub/genai-stack pull request #67
Opened 2023-09-28 11:58 UTC by lucifertrj

- This model supports 32k tokens with GPT4 model

2023-09-28 12:09 UTC, nikhilaiplanet requested changes

2023-09-28 12:09 UTC, nikhilaiplanet commented on genai_stack/model/azurechat.py
> +            openai_api_type="azure",
hardcode openai_api_type & 

`
AzureChatOpenAI(
            openai_api_type="azure",
            **self.config.parameters.dict()
)

`

2023-09-28 12:14 UTC, nikhilaiplanet requested changes

2023-09-29 19:04 UTC, lucifertrj commented
Made the changes. Please review it now

2023-10-01 09:40 UTC, closed without merging